# Generated by Django 5.0.7 on 2024-08-29 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ProductTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='OrderTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('price', models.IntegerField()),
                ('status', models.CharField(max_length=30)),
                ('USER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='My_App.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
                ('ORDER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='My_App.ordertable')),
                ('PRODUCT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='My_App.producttable')),
            ],
        ),
        migrations.CreateModel(
            name='OfferTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('offers', models.FloatField()),
                ('date', models.DateField()),
                ('PRODUCT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='My_App.producttable')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=200)),
                ('ratings', models.CharField(max_length=50)),
                ('reply', models.CharField(max_length=150)),
                ('USER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='My_App.logintable')),
                ('PRODUCT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='My_App.producttable')),
            ],
        ),
        migrations.CreateModel(
            name='SellerTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=30)),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=30)),
                ('image', models.FileField(upload_to='')),
                ('LOGIN_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='My_App.logintable')),
            ],
        ),
        migrations.AddField(
            model_name='producttable',
            name='SELLER_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='My_App.sellertable'),
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('gender', models.CharField(max_length=10)),
                ('image', models.FileField(upload_to='')),
                ('place', models.CharField(max_length=25)),
                ('pin', models.BigIntegerField()),
                ('post', models.CharField(max_length=25)),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=30)),
                ('LOGIN_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='My_App.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('reply', models.CharField(max_length=200)),
                ('USER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='My_App.usertable')),
            ],
        ),
    ]
