# Generated by Django 5.0.7 on 2024-09-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellertable',
            name='id_proof',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
