# Generated by Django 5.0.7 on 2024-10-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0002_sellertable_id_proof'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordertable',
            old_name='price',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='date',
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
