# Generated by Django 5.0.7 on 2024-10-09 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0003_rename_price_ordertable_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacktable',
            name='USER_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='My_App.usertable'),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='USER_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='My_App.usertable'),
        ),
    ]
