# Generated by Django 5.0.7 on 2024-10-10 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0004_alter_feedbacktable_user_id_alter_ordertable_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbacktable',
            name='reply',
        ),
    ]
