# Generated by Django 5.0.7 on 2024-10-11 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0005_remove_feedbacktable_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbacktable',
            name='PRODUCT_ID',
        ),
        migrations.AddField(
            model_name='feedbacktable',
            name='ORDERS',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='My_App.orderdetails'),
            preserve_default=False,
        ),
    ]
