# Generated by Django 5.0.7 on 2024-10-11 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0006_remove_feedbacktable_product_id_feedbacktable_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbacktable',
            name='ORDERS',
        ),
        migrations.AddField(
            model_name='feedbacktable',
            name='PRODUCT',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='My_App.producttable'),
            preserve_default=False,
        ),
    ]
