# Generated by Django 5.1.1 on 2024-10-31 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0007_remove_feedbacktable_orders_feedbacktable_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttable',
            name='Date',
            field=models.DateField(default='2024-10-31'),
            preserve_default=False,
        ),
    ]
