# Generated by Django 5.1.1 on 2024-10-31 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0008_producttable_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHistoryTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Keyword', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('USER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='My_App.usertable')),
            ],
        ),
    ]
