# Generated by Django 5.1.1 on 2024-10-31 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0009_userhistorytable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbacktable',
            name='PRODUCT',
        ),
        migrations.RemoveField(
            model_name='feedbacktable',
            name='USER_ID',
        ),
        migrations.AddField(
            model_name='feedbacktable',
            name='ORDER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='My_App.ordertable'),
            preserve_default=False,
        ),
    ]
