# Generated by Django 5.1.1 on 2024-10-31 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0010_remove_feedbacktable_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbacktable',
            old_name='ORDER',
            new_name='Order',
        ),
        migrations.AddField(
            model_name='feedbacktable',
            name='PRODUCT',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='My_App.producttable'),
            preserve_default=False,
        ),
    ]
