# Generated by Django 5.1.1 on 2024-10-31 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0011_rename_order_feedbacktable_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbacktable',
            old_name='Order',
            new_name='ORDER',
        ),
        migrations.RemoveField(
            model_name='feedbacktable',
            name='PRODUCT',
        ),
    ]
