# Generated by Django 5.1.1 on 2024-10-31 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0012_rename_order_feedbacktable_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbacktable',
            name='ORDER',
        ),
        migrations.AddField(
            model_name='feedbacktable',
            name='ORDERDETAILS',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='My_App.orderdetails'),
            preserve_default=False,
        ),
    ]
