# Generated by Django 5.1.1 on 2024-10-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0013_remove_feedbacktable_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertable',
            name='amount',
            field=models.FloatField(),
        ),
    ]
